### ISSUE TITLE
Docs: include subgraph reference to goerli

### ISSUE THREAD

**Issue by almndbtr** [ourzora/zora-drops-contracts#59]
## Summary

In the README's [`How do I integrate these in my own site?`](https://github.com/ourzora/zora-drops-contracts#how-do-i-integrate-these-in-my-own-site), step 2 says:

> Use our subgraph to find media / metadata information (rinkeby: https://thegraph.com/hosted-service/subgraph/iainnash/erc721droprinkeby) (mainnet: https://thegraph.com/hosted-service/subgraph/iainnash/zora-editions-mainnet)

As of September 2, 2022, `https://testnet.create.zora.co/` only supports the Goerli testnet (which in turn means that the Rinkeby testnet was deprecated).

I think it would be helpful to update step 2 to replace the rinkeby information with the goerli link -- could
https://api.thegraph.com/subgraphs/name/iainnash/erc721drop-goerli be the correct one? 💭

(Originally discovered in [a component in the `0xTranqui/present-materials` repo](https://github.com/0xTranqui/present-materials/blob/f546c915c4c0747e49bbdf5c6995b610e3b7666e/components/EditionCard.tsx#L17))

**Comment by iainnash** [comment]
Yep! this is a great callout.

**Comment by iainnash** [comment]
Fixed :).

**Comment by almndbtr** [comment]
@iainnash Thank you 🙏🏾
